services:
  # PHP Application
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
        NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
        NEW_RELIC_DAEMON_ADDRESS: ${NEW_RELIC_DAEMON_ADDRESS}
        NEW_RELIC_AGENT_VERSION: ${NEW_RELIC_AGENT_VERSION}
    container_name: payment-asaas-php
    restart: unless-stopped
    working_dir: /var/www
    entrypoint: ["/usr/local/bin/docker-php-entrypoint-custom"]
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      NEW_RELIC_DAEMON_ADDRESS: ${NEW_RELIC_DAEMON_ADDRESS}
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - payment-asaas-network
    depends_on:
      - mysql
      - newrelic
      - redis

  # Nginx Service
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: payment-asaas-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - payment-asaas-network
    depends_on:
      - php

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: payment-asaas-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - payment-asaas-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: payment-asaas-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - payment-asaas-network

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: payment-asaas-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    networks:
      - payment-asaas-network

  # Queue Worker Service
  worker:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
        NEW_RELIC_APP_NAME: "${NEW_RELIC_APP_NAME} Worker"
        NEW_RELIC_DAEMON_ADDRESS: ${NEW_RELIC_DAEMON_ADDRESS}
        NEW_RELIC_AGENT_VERSION: ${NEW_RELIC_AGENT_VERSION}
    container_name: payment-asaas-worker
    restart: unless-stopped
    working_dir: /var/www
    entrypoint: ["/usr/local/bin/docker-php-entrypoint-custom"]
    command: php artisan queue:work rabbitmq --queue=payments
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: "${NEW_RELIC_APP_NAME} Worker"
      NEW_RELIC_DAEMON_ADDRESS: ${NEW_RELIC_DAEMON_ADDRESS}
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - payment-asaas-network
    depends_on:
      - php
      - rabbitmq
      - newrelic
      - redis

  # NewRelic Service
  newrelic:
    image: newrelic/php-daemon:latest
    container_name: payment-asaas-newrelic
    restart: unless-stopped
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME:-Payment Asaas API}
    ports:
      - "31339:31339"
    networks:
      - payment-asaas-network
    volumes:
      - newrelic-logs:/var/log/newrelic

  # Horizon Service
  horizon:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
        NEW_RELIC_APP_NAME: "${NEW_RELIC_APP_NAME} Horizon"
        NEW_RELIC_DAEMON_ADDRESS: ${NEW_RELIC_DAEMON_ADDRESS}
        NEW_RELIC_AGENT_VERSION: ${NEW_RELIC_AGENT_VERSION}
    container_name: payment-asaas-horizon
    restart: unless-stopped
    working_dir: /var/www
    entrypoint: ["/usr/local/bin/docker-php-entrypoint-custom"]
    command: php artisan horizon
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: "${NEW_RELIC_APP_NAME} Horizon"
      NEW_RELIC_DAEMON_ADDRESS: ${NEW_RELIC_DAEMON_ADDRESS}
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - payment-asaas-network
    depends_on:
      - php
      - rabbitmq
      - newrelic
      - redis

networks:
  payment-asaas-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  newrelic-logs:
    driver: local
