version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: payment-asaas-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - payment-asaas-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: payment-asaas-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    networks:
      - payment-asaas-network
    depends_on:
      - mysql

networks:
  payment-asaas-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
